version: '2'
services:
  bot:
    image: arbisoft/hubot-rocketchat
    volumes:
    - /home/ubuntu/crackbot-scripts/scripts:/home/hubot/scripts
    links:
    - redis
    environment:
    - REDIS_URL=redis://redis:6379
    - ROCKETCHAT_URL=https://chat.arbisoft.com
    - ROCKETCHAT_ROOM=
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_USER=crackbot
    - ROCKETCHAT_PASSWORD=
    - ROCKETCHAT_AUTH=password
    - HUBOT_REMIND_KEY=WYWGSDGSGGWSTEW4564654
    - HUBOT_TEAM_ADMIN=yasser.bashir
    - BOT_NAME=crackbot
    - EXTERNAL_SCRIPTS=hubot-tell,hubot-standup-alarm,hubot-remind-advanced,hubot-help,hubot-team,hubot-redis-brain,hubot-redis-brain-docker
    - SET_CONTAINER_TIMEZONE=true
    - CONTAINER_TIMEZONE=Asia/Karachi
    - RESPOND_TO_DM=true
  redis:
    image: redis
    ports:
    - "6379"
    volumes:
    - /home/ubuntu/data:/data
    command: redis-server --appendonly yes
    environment:
    - SET_CONTAINER_TIMEZONE=true
    - CONTAINER_TIMEZONE=Asia/Karachi
volumes:
  logvolume01: {}

